# Numpy

In [2]:
import numpy as np

# Numpy Array

In [61]:
list = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [62]:
type(list)

list

In [63]:
array = np.array(list)

In [64]:
type(array)

numpy.ndarray

In [65]:
matrix_1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [66]:
np.array(matrix_1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Hazır Metotlar

In [67]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [69]:
matrix_2=np.arange(5,50,5).reshape(3,3)

In [70]:
matrix_2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [71]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [72]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Random

In [74]:
np.random.rand(5)

array([0.00682573, 0.76979303, 0.7467671 , 0.37743894, 0.49414745])

In [75]:
np.random.rand(3,3)

array([[0.92894839, 0.39545404, 0.9739563 ],
       [0.52441472, 0.09361309, 0.81330841],
       [0.21168679, 0.55434578, 0.29226912]])

In [76]:
np.random.randn(4,4)

array([[ 0.43922896,  0.42329531,  0.62987705, -1.21084259],
       [-0.18483556, -0.84704068, -0.11980861, -1.47710775],
       [-0.05607609, -0.08939501, -1.24318493,  0.1953268 ],
       [ 0.07530821,  0.76739873,  0.03174568, -0.58476825]])

In [77]:
np.random.randint(0,100)

61

In [78]:
np.random.randint(100,1000,5)

array([623, 839, 214, 596, 522])

In [79]:
np.random.seed(99)
np.random.rand(4)

array([0.67227856, 0.4880784 , 0.82549517, 0.03144639])

In [80]:
np.random.rand(4)

array([0.80804996, 0.56561742, 0.2976225 , 0.04669572])

## Max Min

In [81]:
np.random.seed(99)
random=np.random.randint(0,100,15)
random

array([ 1, 35, 57, 40, 73, 82, 68, 69, 52,  1, 23, 35, 55, 65, 48])

In [82]:
random.max()

82

In [83]:
random.min()

1

In [84]:
random.argmax()

5

# Shape & Type

In [85]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [86]:
array.shape

(20,)

In [89]:
array = array.reshape(1,20)

In [90]:
array.shape

(1, 20)

In [91]:
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [92]:
array = array.reshape(20,1)

In [93]:
array

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [94]:
array.shape

(20, 1)

In [95]:
array = array.reshape(5,4)

In [96]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [97]:
array.dtype

dtype('int32')

In [99]:
array_float =np.linspace(14,88,22)
array_float

array([14.        , 17.52380952, 21.04761905, 24.57142857, 28.0952381 ,
       31.61904762, 35.14285714, 38.66666667, 42.19047619, 45.71428571,
       49.23809524, 52.76190476, 56.28571429, 59.80952381, 63.33333333,
       66.85714286, 70.38095238, 73.9047619 , 77.42857143, 80.95238095,
       84.47619048, 88.        ])

In [100]:
array_float.dtype

dtype('float64')

# İşlem

In [101]:
arr_2d=np.arange(10,100,10).reshape(3,3)
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [102]:
islem_arr = arr_2d

In [103]:
islem_arr +5

array([[15, 25, 35],
       [45, 55, 65],
       [75, 85, 95]])

In [104]:
islem_arr * 8

array([[ 80, 160, 240],
       [320, 400, 480],
       [560, 640, 720]])

In [105]:
islem_arr-2

array([[ 8, 18, 28],
       [38, 48, 58],
       [68, 78, 88]])

In [106]:
islem_arr/0

C:\Users\Ahmet\AppData\Local\Temp\ipykernel_19884\89545611.py:1: RuntimeWarning: divide by zero encountered in divide
  islem_arr/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [107]:
np.sqrt(islem_arr)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669],
       [8.36660027, 8.94427191, 9.48683298]])

In [108]:
np.cos(islem_arr)

array([[-0.83907153,  0.40808206,  0.15425145],
       [-0.66693806,  0.96496603, -0.95241298],
       [ 0.6333192 , -0.11038724, -0.44807362]])

## Index İslemleri

In [109]:
idx_arr = np.arange(0,10)

In [110]:
idx_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
idx_arr[4]

4

In [112]:
idx_arr[2:5]

array([2, 3, 4])

In [114]:
idx_arr[2:5] = 99
idx_arr

array([ 0,  1, 99, 99, 99,  5,  6,  7,  8,  9])

In [116]:
idx_part = idx_arr[2:5]

In [117]:
idx_part

array([99, 99, 99])

In [118]:
idx_part[:] = 7
idx_part

array([7, 7, 7])

In [119]:
idx_arr

array([0, 1, 7, 7, 7, 5, 6, 7, 8, 9])

In [120]:
idx_copy = idx_arr.copy()
idx_copy

array([0, 1, 7, 7, 7, 5, 6, 7, 8, 9])

In [121]:
idx_arr < 6

array([ True,  True, False, False, False,  True, False, False, False,
       False])